### ISSUE TITLE
When is the simulator available?

### ISSUE THREAD

**Issue by TMats** [AdaCompNUS/DaXBench#1]
Hello, authors!

I'm amazed by your paper and would like to try the simulator.
When are you going to make the code open-sourced?

**Comment by siwei0729** [comment]
Hello!

Thank you for your interest in our paper and simulator! We are excited to announce that we plan to make the code open-sourced in just one week. We appreciate your patience and hope you'll find the simulator helpful and enjoyable to use.

Best regards!

**Comment by TMats** [comment]
Thank you very much! I'm looking forward to trying your sim!
