### ISSUE TITLE
Is apg cannot be applied in ShapeRopeEnv?

### ISSUE THREAD

**Issue by Norweig1an** [AdaCompNUS/DaXBench#2]
Thanks for your contribution, that's awesome!
However I'm trying to sim different Env like  python -m daxbench.algorithms.apg.apg \
       --env shape_rope \ 
       --ep_len 3 \
       --num_envs 1 \
       --lr 1e-4 \
       --gpus 1 \
       --max_grad_norm 0.3 \
       --seed 0 \
       --eval_freq 200
I got Error **flax.errors.ScopeParamShapeError: Initializer expected to generate shape (3540, 512) but got shape (3891, 512) instead for parameter "kernel" in "/hidden_0".** I try to fix it but cannot clearly understand how 3891 was computed, could you fix it?

**Comment by siwei0729** [comment]
Thank you for reporting this bug! We will fix it as soon as possible. Probably in a few days.

**Comment by siwei0729** [comment]
The observation size issue has been fixed. Thanks.
