### ISSUE TITLE
How to add a more complex 7-DoF robot 

### ISSUE THREAD

**Issue by YantianZha** [AdaCompNUS/DaXBench#6]
Dear Authors,

Thanks for the great work. I was wondering how to modify the code if I want to use a more complex 7-DoF manipulator? Since I tend to define my action space based on the translation and rotation of the gripper, I also don't know if there is any motion planning in the current code. I found the following codes:
core/utils/load_utils.py:import urdfpy
core/utils/load_utils.py:def urdf_add_collision(builder, link, collisions, shape_ke, shape_kd, shape_kf, shape_mu):
core/utils/load_utils.py:        origin = urdfpy.matrix_to_xyz_rpy(collision.origin)
core/utils/load_utils.py:def urdf_load(
core/utils/load_utils.py:    robot = urdfpy.URDF.load(filename)
core/utils/load_utils.py:    urdf_add_collision(builder, root, robot.links[0].collisions, shape_ke, shape_kd, shape_kf, shape_mu)
core/utils/load_utils.py:        origin = urdfpy.matrix_to_xyz_rpy(joint.origin)
core/utils/load_utils.py:        urdf_add_collision(builder, link, robot.link_map[joint.child].collisions, shape_ke, shape_kd, shape_kf, shape_mu)

Is it possible for me to use PyBullet's APIs to load a robot and perform motion planning etc. within your simulator? Or there are better ways?

Thank you,
Yantian

**Comment by siwei0729** [comment]
Dear Yantian,

Thank you for your interest in our work. Our system does not directly support the importing of URDF files. The primary reason behind this is the requirement of a fast and efficient signed distance function (SDF). This function is responsible for calculating the distances of numerous points in the 3-dimensional space to the surface of the manipulator for varying robot configurations, an operation that needs to be performed at a significant speed. 

We recognize the complexity and effort needed to implement this feature and, currently, we have not managed to identify an implementation that aligns with the speed and precision requirements that our system necessitates.

We appreciate your interest in our work and apologize for the limitations currently we have. 

Thanks!

**Comment by YantianZha** [comment]
Okay thank you for your clarification!
